{"content":"---\ntitle: \"How to: Cancel a PLINQ Query\"\nms.date: \"03/30/2017\"\nms.technology: dotnet-standard\ndev_langs: \n  - \"csharp\"\n  - \"vb\"\nhelpviewer_keywords: \n  - \"PLINQ queries, how to cancel\"\n  - \"cancellation, PLINQ\"\nms.assetid: 80b14640-edfa-4153-be1b-3e003d3e9c1a\nauthor: \"rpetrusha\"\nms.author: \"ronpet\"\n---\n# How to: Cancel a PLINQ Query\nThe following examples show two ways to cancel a PLINQ query. The first example shows how to cancel a query that consists mostly of data traversal. The second example shows how to cancel a query that contains a user function that is computationally expensive.  \n  \n> [!NOTE]\n>  When \"Just My Code\" is enabled, Visual Studio will break on the line that throws the exception and display an error message that says \"exception not handled by user code.\" This error is benign. You can press F5 to continue from it, and see the exception-handling behavior that is demonstrated in the examples below. To prevent Visual Studio from breaking on the first error, just uncheck the \"Just My Code\" checkbox under **Tools, Options, Debugging, General**.  \n>   \n>  This example is intended to demonstrate usage, and might not run faster than the equivalent sequential LINQ to Objects query. For more information about speedup, see [Understanding Speedup in PLINQ](../../../docs/standard/parallel-programming/understanding-speedup-in-plinq.md).  \n  \n## Example  \n [!code-csharp[PLINQ#16](../../../samples/snippets/csharp/VS_Snippets_Misc/plinq/cs/plinqsamples.cs#16)]\n [!code-vb[PLINQ#16](../../../samples/snippets/visualbasic/VS_Snippets_Misc/plinq/vb/plinqsnippets1.vb#16)]  \n  \n The PLINQ framework does not roll a single <xref:System.OperationCanceledException> into an <xref:System.AggregateException?displayProperty=nameWithType>; the <xref:System.OperationCanceledException> must be handled in a separate catch block. If one or more user delegates throws an OperationCanceledException(externalCT) (by using an external <xref:System.Threading.CancellationToken?displayProperty=nameWithType>) but no other exception, and the query was defined as `AsParallel().WithCancellation(externalCT)`, then PLINQ will issue a single <xref:System.OperationCanceledException> (externalCT) rather than an <xref:System.AggregateException?displayProperty=nameWithType>. However, if one user delegate throws an <xref:System.OperationCanceledException>, and another delegate throws another exception type, then both exceptions will be rolled into an <xref:System.AggregateException>.  \n  \n The general guidance on cancellation is as follows:  \n  \n1.  If you perform user-delegate cancellation you should inform PLINQ about the external <xref:System.Threading.CancellationToken> and throw an <xref:System.OperationCanceledException>(externalCT).  \n  \n2.  If cancellation occurs and no other exceptions are thrown, then you should handle an <xref:System.OperationCanceledException> rather than an <xref:System.AggregateException>.  \n  \n## Example  \n The following example shows how to handle cancellation when you have a computationally expensive function in user code.  \n  \n [!code-csharp[PLINQ#17](../../../samples/snippets/csharp/VS_Snippets_Misc/plinq/cs/plinqsamples.cs#17)]\n [!code-vb[PLINQ#17](../../../samples/snippets/visualbasic/VS_Snippets_Misc/plinq/vb/plinqsnippets1.vb#17)]  \n  \n When you handle the cancellation in user code, you do not have to use <xref:System.Linq.ParallelEnumerable.WithCancellation%2A> in the query definition. However, we recommended that you do this because <xref:System.Linq.ParallelEnumerable.WithCancellation%2A> has no effect on query performance and it enables the cancellation to be handled by query operators and your user code.  \n  \n In order to ensure system responsiveness, we recommend that you check for cancellation around once per millisecond; however, any period up to 10 milliseconds is considered acceptable. This frequency should not have a negative impact on your code's performance.  \n  \n When an enumerator is disposed, for example when code breaks out of a foreach (For Each in Visual Basic) loop that is iterating over query results, then the query is cancelled, but no exception is thrown.  \n  \n## See also\n\n- <xref:System.Linq.ParallelEnumerable>\n- [Parallel LINQ (PLINQ)](../../../docs/standard/parallel-programming/parallel-linq-plinq.md)\n- [Cancellation in Managed Threads](../../../docs/standard/threading/cancellation-in-managed-threads.md)\n","nodes":[{"pos":[4,300],"embed":true,"restype":"x-metadata","content":"title: \"How to: Cancel a PLINQ Query\"\nms.date: \"03/30/2017\"\nms.technology: dotnet-standard\ndev_langs: \n  - \"csharp\"\n  - \"vb\"\nhelpviewer_keywords: \n  - \"PLINQ queries, how to cancel\"\n  - \"cancellation, PLINQ\"\nms.assetid: 80b14640-edfa-4153-be1b-3e003d3e9c1a\nauthor: \"rpetrusha\"\nms.author: \"ronpet\"","nodes":[{"content":"How to: Cancel a PLINQ Query","nodes":[{"pos":[0,28],"content":"How to: Cancel a PLINQ Query","nodes":[{"content":"How to: Cancel a PLINQ Query","pos":[0,28]}]}],"path":["title"],"nosxs":false}],"yml":true},{"pos":[307,335],"content":"How to: Cancel a PLINQ Query","linkify":"How to: Cancel a PLINQ Query","nodes":[{"content":"How to: Cancel a PLINQ Query","pos":[0,28]}]},{"content":"The following examples show two ways to cancel a PLINQ query.","pos":[336,397]},{"content":"The first example shows how to cancel a query that consists mostly of data traversal.","pos":[398,483]},{"content":"The second example shows how to cancel a query that contains a user function that is computationally expensive.","pos":[484,595]},{"pos":[603,1075],"content":"[!NOTE]\n When \"Just My Code\" is enabled, Visual Studio will break on the line that throws the exception and display an error message that says \"exception not handled by user code.\" This error is benign. You can press F5 to continue from it, and see the exception-handling behavior that is demonstrated in the examples below. To prevent Visual Studio from breaking on the first error, just uncheck the \"Just My Code\" checkbox under **Tools, Options, Debugging, General**.","leadings":["","> "],"nodes":[{"content":"When \"Just My Code\" is enabled, Visual Studio will break on the line that throws the exception and display an error message that says \"exception not handled by user code.\" This error is benign. You can press F5 to continue from it, and see the exception-handling behavior that is demonstrated in the examples below. To prevent Visual Studio from breaking on the first error, just uncheck the \"Just My Code\" checkbox under **Tools, Options, Debugging, General**.","pos":[9,470],"nodes":[{"content":"When \"Just My Code\" is enabled, Visual Studio will break on the line that throws the exception and display an error message that says \"exception not handled by user code.\"","pos":[0,171]},{"content":"This error is benign.","pos":[172,193]},{"content":"You can press F5 to continue from it, and see the exception-handling behavior that is demonstrated in the examples below.","pos":[194,315]},{"content":"To prevent Visual Studio from breaking on the first error, just uncheck the \"Just My Code\" checkbox under <bpt id=\"p1\">**</bpt>Tools, Options, Debugging, General<ept id=\"p1\">**</ept>.","pos":[316,461],"source":" To prevent Visual Studio from breaking on the first error, just uncheck the \"Just My Code\" checkbox under **Tools, Options, Debugging, General**."}]}]},{"content":"This example is intended to demonstrate usage, and might not run faster than the equivalent sequential LINQ to Objects query.","pos":[1086,1211]},{"content":"For more information about speedup, see <bpt id=\"p1\">[</bpt>Understanding Speedup in PLINQ<ept id=\"p1\">](../../../docs/standard/parallel-programming/understanding-speedup-in-plinq.md)</ept>.","pos":[1212,1364],"source":" For more information about speedup, see [Understanding Speedup in PLINQ](../../../docs/standard/parallel-programming/understanding-speedup-in-plinq.md)."},{"pos":[1373,1380],"content":"Example","linkify":"Example","nodes":[{"content":"Example","pos":[0,7]}]},{"content":"The PLINQ framework does not roll a single <ph id=\"ph1\">&lt;xref:System.OperationCanceledException&gt;</ph> into an <ph id=\"ph2\">&lt;xref:System.AggregateException?displayProperty=nameWithType&gt;</ph>; the <ph id=\"ph3\">&lt;xref:System.OperationCanceledException&gt;</ph> must be handled in a separate catch block.","pos":[1602,1844],"source":"The PLINQ framework does not roll a single <xref:System.OperationCanceledException> into an <xref:System.AggregateException?displayProperty=nameWithType>; the <xref:System.OperationCanceledException> must be handled in a separate catch block."},{"content":"If one or more user delegates throws an OperationCanceledException(externalCT) (by using an external <ph id=\"ph1\">&lt;xref:System.Threading.CancellationToken?displayProperty=nameWithType&gt;</ph>) but no other exception, and the query was defined as <ph id=\"ph2\">`AsParallel().WithCancellation(externalCT)`</ph>, then PLINQ will issue a single <ph id=\"ph3\">&lt;xref:System.OperationCanceledException&gt;</ph> (externalCT) rather than an <ph id=\"ph4\">&lt;xref:System.AggregateException?displayProperty=nameWithType&gt;</ph>.","pos":[1845,2278],"source":" If one or more user delegates throws an OperationCanceledException(externalCT) (by using an external <xref:System.Threading.CancellationToken?displayProperty=nameWithType>) but no other exception, and the query was defined as `AsParallel().WithCancellation(externalCT)`, then PLINQ will issue a single <xref:System.OperationCanceledException> (externalCT) rather than an <xref:System.AggregateException?displayProperty=nameWithType>."},{"content":"However, if one user delegate throws an <ph id=\"ph1\">&lt;xref:System.OperationCanceledException&gt;</ph>, and another delegate throws another exception type, then both exceptions will be rolled into an <ph id=\"ph2\">&lt;xref:System.AggregateException&gt;</ph>.","pos":[2279,2490],"source":" However, if one user delegate throws an <xref:System.OperationCanceledException>, and another delegate throws another exception type, then both exceptions will be rolled into an <xref:System.AggregateException>."},{"content":"The general guidance on cancellation is as follows:","pos":[2497,2548]},{"pos":[2558,2751],"content":"If you perform user-delegate cancellation you should inform PLINQ about the external <ph id=\"ph1\">&lt;xref:System.Threading.CancellationToken&gt;</ph> and throw an <ph id=\"ph2\">&lt;xref:System.OperationCanceledException&gt;</ph>(externalCT).","source":"If you perform user-delegate cancellation you should inform PLINQ about the external <xref:System.Threading.CancellationToken> and throw an <xref:System.OperationCanceledException>(externalCT)."},{"pos":[2761,2935],"content":"If cancellation occurs and no other exceptions are thrown, then you should handle an <ph id=\"ph1\">&lt;xref:System.OperationCanceledException&gt;</ph> rather than an <ph id=\"ph2\">&lt;xref:System.AggregateException&gt;</ph>.","source":"If cancellation occurs and no other exceptions are thrown, then you should handle an <xref:System.OperationCanceledException> rather than an <xref:System.AggregateException>."},{"pos":[2944,2951],"content":"Example","linkify":"Example","nodes":[{"content":"Example","pos":[0,7]}]},{"content":"The following example shows how to handle cancellation when you have a computationally expensive function in user code.","pos":[2955,3074]},{"content":"When you handle the cancellation in user code, you do not have to use <ph id=\"ph1\">&lt;xref:System.Linq.ParallelEnumerable.WithCancellation%2A&gt;</ph> in the query definition.","pos":[3299,3451],"source":"When you handle the cancellation in user code, you do not have to use <xref:System.Linq.ParallelEnumerable.WithCancellation%2A> in the query definition."},{"content":"However, we recommended that you do this because <ph id=\"ph1\">&lt;xref:System.Linq.ParallelEnumerable.WithCancellation%2A&gt;</ph> has no effect on query performance and it enables the cancellation to be handled by query operators and your user code.","pos":[3452,3678],"source":" However, we recommended that you do this because <xref:System.Linq.ParallelEnumerable.WithCancellation%2A> has no effect on query performance and it enables the cancellation to be handled by query operators and your user code."},{"content":"In order to ensure system responsiveness, we recommend that you check for cancellation around once per millisecond; however, any period up to 10 milliseconds is considered acceptable.","pos":[3685,3868]},{"content":"This frequency should not have a negative impact on your code's performance.","pos":[3869,3945]},{"content":"When an enumerator is disposed, for example when code breaks out of a foreach (For Each in Visual Basic) loop that is iterating over query results, then the query is cancelled, but no exception is thrown.","pos":[3952,4156]},{"pos":[4165,4173],"content":"See also","linkify":"See also","nodes":[{"content":"See also","pos":[0,8]}]},{"pos":[4217,4308],"content":"<bpt id=\"p1\">[</bpt>Parallel LINQ (PLINQ)<ept id=\"p1\">](../../../docs/standard/parallel-programming/parallel-linq-plinq.md)</ept>","source":"[Parallel LINQ (PLINQ)](../../../docs/standard/parallel-programming/parallel-linq-plinq.md)"},{"pos":[4311,4413],"content":"<bpt id=\"p1\">[</bpt>Cancellation in Managed Threads<ept id=\"p1\">](../../../docs/standard/threading/cancellation-in-managed-threads.md)</ept>","source":"[Cancellation in Managed Threads](../../../docs/standard/threading/cancellation-in-managed-threads.md)"}]}