{"content":"---\ntitle: \"Creating and Throwing Exceptions (C# Programming Guide) | Microsoft Docs\"\n\nms.date: \"2015-07-20\"\nms.prod: .net\n\n\nms.technology: \n  - \"devlang-csharp\"\n\nms.topic: \"article\"\ndev_langs: \n  - \"CSharp\"\nhelpviewer_keywords: \n  - \"catching exceptions [C#]\"\n  - \"throwing exceptions [C#]\"\n  - \"exceptions [C#], creating\"\n  - \"exceptions [C#], throwing\"\nms.assetid: 6bbba495-a115-4c6d-90cc-1f4d7b5f39e2\ncaps.latest.revision: 28\nauthor: \"BillWagner\"\nms.author: \"wiwagn\"\n\ntranslation.priority.ht: \n  - \"cs-cz\"\n  - \"de-de\"\n  - \"es-es\"\n  - \"fr-fr\"\n  - \"it-it\"\n  - \"ja-jp\"\n  - \"ko-kr\"\n  - \"pl-pl\"\n  - \"pt-br\"\n  - \"ru-ru\"\n  - \"tr-tr\"\n  - \"zh-cn\"\n  - \"zh-tw\"\n---\n# Creating and Throwing Exceptions (C# Programming Guide)\nExceptions are used to indicate that an error has occurred while running the program. Exception objects that describe an error are created and then *thrown* with the [throw](../../../csharp/language-reference/keywords/throw.md) keyword. The runtime then searches for the most compatible exception handler.  \n  \n Programmers should throw exceptions when one or more of the following conditions are true:  \n  \n-   The method cannot complete its defined functionality.  \n  \n     For example, if a parameter to a method has an invalid value:  \n  \n     [!code-cs[csProgGuideExceptions#12](../../../csharp/programming-guide/exceptions/codesnippet/CSharp/creating-and-throwing-exceptions_1.cs)]  \n  \n-   An inappropriate call to an object is made, based on the object state.  \n  \n     One example might be trying to write to a read-only file. In cases where an object state does not allow an operation, throw an instance of <xref:System.InvalidOperationException> or an object based on a derivation of this class. This is an example of a method that throws an <xref:System.InvalidOperationException> object:  \n  \n     [!code-cs[csProgGuideExceptions#13](../../../csharp/programming-guide/exceptions/codesnippet/CSharp/creating-and-throwing-exceptions_2.cs)]  \n  \n-   When an argument to a method causes an exception.  \n  \n     In this case, the original exception should be caught and an <xref:System.ArgumentException> instance should be created. The original exception should be passed to the constructor of the <xref:System.ArgumentException> as the <xref:System.Exception.InnerException%2A> parameter:  \n  \n     [!code-cs[csProgGuideExceptions#14](../../../csharp/programming-guide/exceptions/codesnippet/CSharp/creating-and-throwing-exceptions_3.cs)]  \n  \n Exceptions contain a property named <xref:System.Exception.StackTrace%2A>. This string contains the name of the methods on the current call stack, together with the file name and line number where the exception was thrown for each method. A <xref:System.Exception.StackTrace%2A> object is created automatically by the common language runtime (CLR) from the point of the `throw` statement, so that exceptions must be thrown from the point where the stack trace should begin.  \n  \n All exceptions contain a property named <xref:System.Exception.Message%2A>. This string should be set to explain the reason for the exception. Note that information that is sensitive to security should not be put in the message text. In addition to <xref:System.Exception.Message%2A>, <xref:System.ArgumentException> contains a property named <xref:System.ArgumentException.ParamName%2A> that should be set to the name of the argument that caused the exception to be thrown. In the case of a property setter, <xref:System.ArgumentException.ParamName%2A> should be set to `value`.  \n  \n Public and protected methods members should throw exceptions whenever they cannot complete their intended functions. The exception class that is thrown should be the most specific exception available that fits the error conditions. These exceptions should be documented as part of the class functionality, and derived classes or updates to the original class should retain the same behavior for backward compatibility.  \n  \n## Things to Avoid When Throwing Exceptions  \n The following list identifies practices to avoid when throwing exceptions:  \n  \n-   Exceptions should not be used to change the flow of a program as part of ordinary execution. Exceptions should only be used to report and handle error conditions.  \n  \n-   Exceptions should not be returned as a return value or parameter instead of being thrown.  \n  \n-   Do not throw <xref:System.Exception?displayProperty=fullName>, <xref:System.SystemException?displayProperty=fullName>, <xref:System.NullReferenceException?displayProperty=fullName>, or <xref:System.IndexOutOfRangeException?displayProperty=fullName> intentionally from your own source code.  \n  \n-   Do not create exceptions that can be thrown in debug mode but not release mode. To identify run-time errors during the development phase, use Debug Assert instead.  \n  \n## Defining Exception Classes  \n Programs can throw a predefined exception class in the <xref:System> namespace (except where previously noted), or create their own exception classes by deriving from <xref:System.Exception>. The derived classes should define at least four constructors: one default constructor, one that sets the message property, and one that sets both the <xref:System.Exception.Message%2A> and <xref:System.Exception.InnerException%2A> properties. The fourth constructor is used to serialize the exception. New exception classes should be serializable. For example:  \n  \n [!code-cs[csProgGuideExceptions#15](../../../csharp/programming-guide/exceptions/codesnippet/CSharp/creating-and-throwing-exceptions_4.cs)]  \n  \n New properties should only be added to the exception class when the data they provide is useful to resolving the exception. If new properties are added to the derived exception class, `ToString()` should be overridden to return the added information.  \n  \n## C# Language Specification  \n [!INCLUDE[CSharplangspec](../../../csharp/language-reference/keywords/includes/csharplangspec_md.md)]  \n  \n## See Also  \n [C# Programming Guide](../../../csharp/programming-guide/index.md)   \n [Exceptions and Exception Handling](../../../csharp/programming-guide/exceptions/index.md)   \n [Exception Hierarchy](http://msdn.microsoft.com/library/f7d68675-be06-40fb-a555-05f0c5a6f66b)   \n [Exception Handling](../../../csharp/programming-guide/exceptions/exception-handling.md)","nodes":[{"pos":[4,653],"embed":true,"restype":"x-metadata","content":"title: \"Creating and Throwing Exceptions (C# Programming Guide) | Microsoft Docs\"\n\nms.date: \"2015-07-20\"\nms.prod: .net\n\n\nms.technology: \n  - \"devlang-csharp\"\n\nms.topic: \"article\"\ndev_langs: \n  - \"CSharp\"\nhelpviewer_keywords: \n  - \"catching exceptions [C#]\"\n  - \"throwing exceptions [C#]\"\n  - \"exceptions [C#], creating\"\n  - \"exceptions [C#], throwing\"\nms.assetid: 6bbba495-a115-4c6d-90cc-1f4d7b5f39e2\ncaps.latest.revision: 28\nauthor: \"BillWagner\"\nms.author: \"wiwagn\"\n\ntranslation.priority.ht: \n  - \"cs-cz\"\n  - \"de-de\"\n  - \"es-es\"\n  - \"fr-fr\"\n  - \"it-it\"\n  - \"ja-jp\"\n  - \"ko-kr\"\n  - \"pl-pl\"\n  - \"pt-br\"\n  - \"ru-ru\"\n  - \"tr-tr\"\n  - \"zh-cn\"\n  - \"zh-tw\"","nodes":[{"content":"Creating and Throwing Exceptions (C# Programming Guide) | Microsoft Docs","nodes":[{"pos":[0,72],"content":"Creating and Throwing Exceptions (C# Programming Guide) | Microsoft Docs","nodes":[{"content":"Creating and Throwing Exceptions (C# Programming Guide) | Microsoft Docs","pos":[0,72]}]}],"path":["title"]}],"yml":true},{"pos":[660,715],"content":"Creating and Throwing Exceptions (C# Programming Guide)","linkify":"Creating and Throwing Exceptions (C# Programming Guide)","nodes":[{"content":"Creating and Throwing Exceptions (C# Programming Guide)","pos":[0,55]}]},{"content":"Exceptions are used to indicate that an error has occurred while running the program.","pos":[716,801]},{"content":"Exception objects that describe an error are created and then <bpt id=\"p1\">*</bpt>thrown<ept id=\"p1\">*</ept> with the <bpt id=\"p2\">[</bpt>throw<ept id=\"p2\">](../../../csharp/language-reference/keywords/throw.md)</ept> keyword.","pos":[802,952],"source":" Exception objects that describe an error are created and then *thrown* with the [throw](../../../csharp/language-reference/keywords/throw.md) keyword."},{"content":"The runtime then searches for the most compatible exception handler.","pos":[953,1021]},{"content":"Programmers should throw exceptions when one or more of the following conditions are true:","pos":[1028,1118]},{"content":"The method cannot complete its defined functionality.","pos":[1128,1181]},{"content":"For example, if a parameter to a method has an invalid value:","pos":[1192,1253]},{"content":"An inappropriate call to an object is made, based on the object state.","pos":[1413,1483]},{"content":"One example might be trying to write to a read-only file.","pos":[1494,1551]},{"content":"In cases where an object state does not allow an operation, throw an instance of <ph id=\"ph1\">&lt;xref:System.InvalidOperationException&gt;</ph> or an object based on a derivation of this class.","pos":[1552,1722],"source":" In cases where an object state does not allow an operation, throw an instance of <xref:System.InvalidOperationException> or an object based on a derivation of this class."},{"content":"This is an example of a method that throws an <ph id=\"ph1\">&lt;xref:System.InvalidOperationException&gt;</ph> object:","pos":[1723,1816],"source":" This is an example of a method that throws an <xref:System.InvalidOperationException> object:"},{"content":"When an argument to a method causes an exception.","pos":[1976,2025]},{"content":"In this case, the original exception should be caught and an <ph id=\"ph1\">&lt;xref:System.ArgumentException&gt;</ph> instance should be created.","pos":[2036,2156],"source":"In this case, the original exception should be caught and an <xref:System.ArgumentException> instance should be created."},{"content":"The original exception should be passed to the constructor of the <ph id=\"ph1\">&lt;xref:System.ArgumentException&gt;</ph> as the <ph id=\"ph2\">&lt;xref:System.Exception.InnerException%2A&gt;</ph> parameter:","pos":[2157,2314],"source":" The original exception should be passed to the constructor of the <xref:System.ArgumentException> as the <xref:System.Exception.InnerException%2A> parameter:"},{"content":"Exceptions contain a property named <ph id=\"ph1\">&lt;xref:System.Exception.StackTrace%2A&gt;</ph>.","pos":[2471,2545],"source":"Exceptions contain a property named <xref:System.Exception.StackTrace%2A>."},{"content":"This string contains the name of the methods on the current call stack, together with the file name and line number where the exception was thrown for each method.","pos":[2546,2709]},{"content":"A <ph id=\"ph1\">&lt;xref:System.Exception.StackTrace%2A&gt;</ph> object is created automatically by the common language runtime (CLR) from the point of the <ph id=\"ph2\">`throw`</ph> statement, so that exceptions must be thrown from the point where the stack trace should begin.","pos":[2710,2944],"source":" A <xref:System.Exception.StackTrace%2A> object is created automatically by the common language runtime (CLR) from the point of the `throw` statement, so that exceptions must be thrown from the point where the stack trace should begin."},{"content":"All exceptions contain a property named <ph id=\"ph1\">&lt;xref:System.Exception.Message%2A&gt;</ph>.","pos":[2951,3026],"source":"All exceptions contain a property named <xref:System.Exception.Message%2A>."},{"content":"This string should be set to explain the reason for the exception.","pos":[3027,3093]},{"content":"Note that information that is sensitive to security should not be put in the message text.","pos":[3094,3184]},{"content":"In addition to <ph id=\"ph1\">&lt;xref:System.Exception.Message%2A&gt;</ph>, <ph id=\"ph2\">&lt;xref:System.ArgumentException&gt;</ph> contains a property named <ph id=\"ph3\">&lt;xref:System.ArgumentException.ParamName%2A&gt;</ph> that should be set to the name of the argument that caused the exception to be thrown.","pos":[3185,3425],"source":" In addition to <xref:System.Exception.Message%2A>, <xref:System.ArgumentException> contains a property named <xref:System.ArgumentException.ParamName%2A> that should be set to the name of the argument that caused the exception to be thrown."},{"content":"In the case of a property setter, <ph id=\"ph1\">&lt;xref:System.ArgumentException.ParamName%2A&gt;</ph> should be set to <ph id=\"ph2\">`value`</ph>.","pos":[3426,3530],"source":" In the case of a property setter, <xref:System.ArgumentException.ParamName%2A> should be set to `value`."},{"content":"Public and protected methods members should throw exceptions whenever they cannot complete their intended functions.","pos":[3537,3653]},{"content":"The exception class that is thrown should be the most specific exception available that fits the error conditions.","pos":[3654,3768]},{"content":"These exceptions should be documented as part of the class functionality, and derived classes or updates to the original class should retain the same behavior for backward compatibility.","pos":[3769,3955]},{"pos":[3964,4004],"content":"Things to Avoid When Throwing Exceptions","linkify":"Things to Avoid When Throwing Exceptions","nodes":[{"content":"Things to Avoid When Throwing Exceptions","pos":[0,40]}]},{"content":"The following list identifies practices to avoid when throwing exceptions:","pos":[4008,4082]},{"content":"Exceptions should not be used to change the flow of a program as part of ordinary execution.","pos":[4092,4184]},{"content":"Exceptions should only be used to report and handle error conditions.","pos":[4185,4254]},{"content":"Exceptions should not be returned as a return value or parameter instead of being thrown.","pos":[4264,4353]},{"content":"Do not throw <ph id=\"ph1\">&lt;xref:System.Exception?displayProperty=fullName&gt;</ph>, <ph id=\"ph2\">&lt;xref:System.SystemException?displayProperty=fullName&gt;</ph>, <ph id=\"ph3\">&lt;xref:System.NullReferenceException?displayProperty=fullName&gt;</ph>, or <ph id=\"ph4\">&lt;xref:System.IndexOutOfRangeException?displayProperty=fullName&gt;</ph> intentionally from your own source code.","pos":[4363,4652],"source":"Do not throw <xref:System.Exception?displayProperty=fullName>, <xref:System.SystemException?displayProperty=fullName>, <xref:System.NullReferenceException?displayProperty=fullName>, or <xref:System.IndexOutOfRangeException?displayProperty=fullName> intentionally from your own source code."},{"content":"Do not create exceptions that can be thrown in debug mode but not release mode.","pos":[4662,4741]},{"content":"To identify run-time errors during the development phase, use Debug Assert instead.","pos":[4742,4825]},{"pos":[4834,4860],"content":"Defining Exception Classes","linkify":"Defining Exception Classes","nodes":[{"content":"Defining Exception Classes","pos":[0,26]}]},{"content":"Programs can throw a predefined exception class in the <ph id=\"ph1\">&lt;xref:System&gt;</ph> namespace (except where previously noted), or create their own exception classes by deriving from <ph id=\"ph2\">&lt;xref:System.Exception&gt;</ph>.","pos":[4864,5055],"source":"Programs can throw a predefined exception class in the <xref:System> namespace (except where previously noted), or create their own exception classes by deriving from <xref:System.Exception>."},{"content":"The derived classes should define at least four constructors: one default constructor, one that sets the message property, and one that sets both the <ph id=\"ph1\">&lt;xref:System.Exception.Message%2A&gt;</ph> and <ph id=\"ph2\">&lt;xref:System.Exception.InnerException%2A&gt;</ph> properties.","pos":[5056,5298],"source":" The derived classes should define at least four constructors: one default constructor, one that sets the message property, and one that sets both the <xref:System.Exception.Message%2A> and <xref:System.Exception.InnerException%2A> properties."},{"content":"The fourth constructor is used to serialize the exception.","pos":[5299,5357]},{"content":"New exception classes should be serializable.","pos":[5358,5403]},{"content":"For example:","pos":[5404,5416]},{"content":"New properties should only be added to the exception class when the data they provide is useful to resolving the exception.","pos":[5569,5692]},{"content":"If new properties are added to the derived exception class, <ph id=\"ph1\">`ToString()`</ph> should be overridden to return the added information.","pos":[5693,5819],"source":" If new properties are added to the derived exception class, `ToString()` should be overridden to return the added information."},{"pos":[5828,5853],"content":"C# Language Specification","linkify":"C# Language Specification","nodes":[{"content":"C# Language Specification","pos":[0,25]}]},{"pos":[5967,5975],"content":"See Also","linkify":"See Also","nodes":[{"content":"See Also","pos":[0,8]}]},{"content":"<bpt id=\"p1\">[</bpt>C# Programming Guide<ept id=\"p1\">](../../../csharp/programming-guide/index.md)</ept><ph id=\"ph1\"> </ph>","pos":[5979,6046],"source":"[C# Programming Guide](../../../csharp/programming-guide/index.md) "},{"content":"<bpt id=\"p1\">[</bpt>Exceptions and Exception Handling<ept id=\"p1\">](../../../csharp/programming-guide/exceptions/index.md)</ept><ph id=\"ph1\"> </ph>","pos":[6050,6141],"source":"[Exceptions and Exception Handling](../../../csharp/programming-guide/exceptions/index.md) "},{"content":"<bpt id=\"p1\">[</bpt>Exception Hierarchy<ept id=\"p1\">](http://msdn.microsoft.com/library/f7d68675-be06-40fb-a555-05f0c5a6f66b)</ept><ph id=\"ph1\"> </ph>","pos":[6145,6239],"source":"[Exception Hierarchy](http://msdn.microsoft.com/library/f7d68675-be06-40fb-a555-05f0c5a6f66b) "},{"content":"<bpt id=\"p1\">[</bpt>Exception Handling<ept id=\"p1\">](../../../csharp/programming-guide/exceptions/exception-handling.md)</ept>","pos":[6243,6331],"source":"[Exception Handling](../../../csharp/programming-guide/exceptions/exception-handling.md)"}]}