{"content":"---\ntitle: \"Compiler-Generated Exceptions - C# Programming Guide\"\nms.custom: seodec18\nms.date: 07/20/2015\nhelpviewer_keywords: \n  - \"exceptions [C#], compiler-generated\"\nms.assetid: 53b52f97-b366-4ed7-b05b-9eb78096b7f9\n---\n# Compiler-Generated Exceptions (C# Programming Guide)\nSome exceptions are thrown automatically by the .NET Framework's common language runtime (CLR) when basic operations fail. These exceptions and their error conditions are listed in the following table.  \n  \n|Exception|Description|  \n|---------------|-----------------|  \n|<xref:System.ArithmeticException>|A base class for exceptions that occur during arithmetic operations, such as <xref:System.DivideByZeroException> and <xref:System.OverflowException>.|  \n|<xref:System.ArrayTypeMismatchException>|Thrown when an array cannot store a given element because the actual type of the element is incompatible with the actual type of the array.|  \n|<xref:System.DivideByZeroException>|Thrown when an attempt is made to divide an integral value by zero.|  \n|<xref:System.IndexOutOfRangeException>|Thrown when an attempt is made to index an array when the index is less than zero or outside the bounds of the array.|  \n|<xref:System.InvalidCastException>|Thrown when an explicit conversion from a base type to an interface or to a derived type fails at runtime.|  \n|<xref:System.NullReferenceException>|Thrown when you attempt to reference an object whose value is [null](../../../csharp/language-reference/keywords/null.md).|  \n|<xref:System.OutOfMemoryException>|Thrown when an attempt to allocate memory using the [new](../../../csharp/language-reference/keywords/new-operator.md) operator fails. This indicates that the memory available to the common language runtime has been exhausted.|  \n|<xref:System.OverflowException>|Thrown when an arithmetic operation in a `checked` context overflows.|  \n|<xref:System.StackOverflowException>|Thrown when the execution stack is exhausted by having too many pending method calls; usually indicates a very deep or infinite recursion.|  \n|<xref:System.TypeInitializationException>|Thrown when a static constructor throws an exception and no compatible `catch` clause exists to catch it.|  \n  \n## See also\n\n- [C# Programming Guide](../../../csharp/programming-guide/index.md)\n- [Exceptions and Exception Handling](../../../csharp/programming-guide/exceptions/index.md)\n- [Exception Handling](../../../csharp/programming-guide/exceptions/exception-handling.md)\n- [try-catch](../../../csharp/language-reference/keywords/try-catch.md)\n- [try-finally](../../../csharp/language-reference/keywords/try-finally.md)\n- [try-catch-finally](../../../csharp/language-reference/keywords/try-catch-finally.md)\n","nodes":[{"pos":[4,218],"embed":true,"restype":"x-metadata","content":"title: \"Compiler-Generated Exceptions - C# Programming Guide\"\nms.custom: seodec18\nms.date: 07/20/2015\nhelpviewer_keywords: \n  - \"exceptions [C#], compiler-generated\"\nms.assetid: 53b52f97-b366-4ed7-b05b-9eb78096b7f9","nodes":[{"content":"Compiler-Generated Exceptions - C# Programming Guide","nodes":[{"pos":[0,52],"content":"Compiler-Generated Exceptions - C# Programming Guide","nodes":[{"content":"Compiler-Generated Exceptions - C# Programming Guide","pos":[0,52]}]}],"path":["title"],"nosxs":false}],"yml":true},{"pos":[225,277],"content":"Compiler-Generated Exceptions (C# Programming Guide)","linkify":"Compiler-Generated Exceptions (C# Programming Guide)","nodes":[{"content":"Compiler-Generated Exceptions (C# Programming Guide)","pos":[0,52]}]},{"content":"Some exceptions are thrown automatically by the .NET Framework's common language runtime (CLR) when basic operations fail.","pos":[278,400]},{"content":"These exceptions and their error conditions are listed in the following table.","pos":[401,479]},{"content":"Exception","pos":[486,495]},{"content":"Description","pos":[496,507]},{"pos":[584,733],"content":"A base class for exceptions that occur during arithmetic operations, such as <ph id=\"ph1\">&lt;xref:System.DivideByZeroException&gt;</ph> and <ph id=\"ph2\">&lt;xref:System.OverflowException&gt;</ph>.","source":"A base class for exceptions that occur during arithmetic operations, such as <xref:System.DivideByZeroException> and <xref:System.OverflowException>."},{"content":"Thrown when an array cannot store a given element because the actual type of the element is incompatible with the actual type of the array.","pos":[779,918]},{"content":"Thrown when an attempt is made to divide an integral value by zero.","pos":[959,1026]},{"content":"Thrown when an attempt is made to index an array when the index is less than zero or outside the bounds of the array.","pos":[1070,1187]},{"content":"Thrown when an explicit conversion from a base type to an interface or to a derived type fails at runtime.","pos":[1227,1333]},{"pos":[1375,1497],"content":"Thrown when you attempt to reference an object whose value is <bpt id=\"p1\">[</bpt>null<ept id=\"p1\">](../../../csharp/language-reference/keywords/null.md)</ept>.","source":"Thrown when you attempt to reference an object whose value is [null](../../../csharp/language-reference/keywords/null.md)."},{"content":"Thrown when an attempt to allocate memory using the <bpt id=\"p1\">[</bpt>new<ept id=\"p1\">](../../../csharp/language-reference/keywords/new-operator.md)</ept> operator fails.","pos":[1537,1671],"source":"Thrown when an attempt to allocate memory using the [new](../../../csharp/language-reference/keywords/new-operator.md) operator fails."},{"content":"This indicates that the memory available to the common language runtime has been exhausted.","pos":[1672,1763]},{"pos":[1800,1869],"content":"Thrown when an arithmetic operation in a <ph id=\"ph1\">`checked`</ph> context overflows.","source":"Thrown when an arithmetic operation in a `checked` context overflows."},{"content":"Thrown when the execution stack is exhausted by having too many pending method calls; usually indicates a very deep or infinite recursion.","pos":[1911,2049]},{"pos":[2096,2201],"content":"Thrown when a static constructor throws an exception and no compatible <ph id=\"ph1\">`catch`</ph> clause exists to catch it.","source":"Thrown when a static constructor throws an exception and no compatible `catch` clause exists to catch it."},{"pos":[2211,2219],"content":"See also","linkify":"See also","nodes":[{"content":"See also","pos":[0,8]}]},{"pos":[2223,2289],"content":"<bpt id=\"p1\">[</bpt>C# Programming Guide<ept id=\"p1\">](../../../csharp/programming-guide/index.md)</ept>","source":"[C# Programming Guide](../../../csharp/programming-guide/index.md)"},{"pos":[2292,2382],"content":"<bpt id=\"p1\">[</bpt>Exceptions and Exception Handling<ept id=\"p1\">](../../../csharp/programming-guide/exceptions/index.md)</ept>","source":"[Exceptions and Exception Handling](../../../csharp/programming-guide/exceptions/index.md)"},{"pos":[2385,2473],"content":"<bpt id=\"p1\">[</bpt>Exception Handling<ept id=\"p1\">](../../../csharp/programming-guide/exceptions/exception-handling.md)</ept>","source":"[Exception Handling](../../../csharp/programming-guide/exceptions/exception-handling.md)"},{"pos":[2476,2545],"content":"<bpt id=\"p1\">[</bpt>try-catch<ept id=\"p1\">](../../../csharp/language-reference/keywords/try-catch.md)</ept>","source":"[try-catch](../../../csharp/language-reference/keywords/try-catch.md)"},{"pos":[2548,2621],"content":"<bpt id=\"p1\">[</bpt>try-finally<ept id=\"p1\">](../../../csharp/language-reference/keywords/try-finally.md)</ept>","source":"[try-finally](../../../csharp/language-reference/keywords/try-finally.md)"},{"pos":[2624,2709],"content":"<bpt id=\"p1\">[</bpt>try-catch-finally<ept id=\"p1\">](../../../csharp/language-reference/keywords/try-catch-finally.md)</ept>","source":"[try-catch-finally](../../../csharp/language-reference/keywords/try-catch-finally.md)"}]}