{"content":"---\ntitle: \"How to: Handle Exceptions in a PLINQ Query\"\nms.date: \"03/30/2017\"\nms.technology: dotnet-standard\ndev_langs: \n  - \"csharp\"\n  - \"vb\"\nhelpviewer_keywords: \n  - \"PLINQ queries, how to handle exceptions\"\nms.assetid: 8d56ff9b-a571-4d31-b41f-80c0b51b70a5\nauthor: \"rpetrusha\"\nms.author: \"ronpet\"\n---\n# How to: Handle Exceptions in a PLINQ Query\nThe first example in this topic shows how to handle the <xref:System.AggregateException?displayProperty=nameWithType> that can be thrown from a PLINQ query when it executes. The second example shows how to put try-catch blocks within delegates, as close as possible to where the exception will be thrown. In this way, you can catch them as soon as they occur and possibly continue query execution. When exceptions are allowed to bubble up back to the joining thread, then it is possible that a query may continue to process some items after the exception is raised.  \n  \n In some cases when PLINQ falls back to sequential execution, and an exception occurs, the exception may be propagated directly, and not wrapped in an <xref:System.AggregateException>. Also, <xref:System.Threading.ThreadAbortException>s are always propagated directly.  \n  \n> [!NOTE]\n>  When \"Just My Code\" is enabled, Visual Studio will break on the line that throws the exception and display an error message that says \"exception not handled by user code.\" This error is benign. You can press F5 to continue from it, and see the exception-handling behavior that is demonstrated in the examples below. To prevent Visual Studio from breaking on the first error, just uncheck the \"Just My Code\" checkbox under **Tools, Options, Debugging, General**.  \n>   \n>  This example is intended to demonstrate usage, and might not run faster than the equivalent sequential LINQ to Objects query. For more information about speedup, see [Understanding Speedup in PLINQ](../../../docs/standard/parallel-programming/understanding-speedup-in-plinq.md).  \n  \n## Example  \n This example shows how to put the try-catch blocks around the code that executes the query to catch any <xref:System.AggregateException?displayProperty=nameWithType>s that are thrown.  \n  \n [!code-csharp[PLINQ#41](../../../samples/snippets/csharp/VS_Snippets_Misc/plinq/cs/plinqsamples.cs#41)]\n [!code-vb[PLINQ#41](../../../samples/snippets/visualbasic/VS_Snippets_Misc/plinq/vb/plinqsnippets1.vb#41)]  \n  \n In this example, the query cannot continue after the exception is thrown. By the time your application code catches the exception, PLINQ has already stopped the query on all threads.  \n  \n## Example  \n The following example shows how to put a try-catch block in a delegate to make it possible to catch an exception and continue with the query execution.  \n  \n [!code-csharp[PLINQ#42](../../../samples/snippets/csharp/VS_Snippets_Misc/plinq/cs/plinqsamples.cs#42)]\n [!code-vb[PLINQ#42](../../../samples/snippets/visualbasic/VS_Snippets_Misc/plinq/vb/plinqsnippets1.vb#42)]  \n  \n## Compiling the Code  \n  \n-   To compile and run these examples, copy them into the PLINQ Data Sample example and call the method from Main.  \n  \n## Robust Programming  \n Do not catch an exception unless you know how to handle it so that you do not corrupt the state of your program.  \n  \n## See also\n\n- <xref:System.Linq.ParallelEnumerable>\n- [Parallel LINQ (PLINQ)](../../../docs/standard/parallel-programming/parallel-linq-plinq.md)\n","nodes":[{"pos":[4,299],"embed":true,"restype":"x-metadata","content":"title: \"How to: Handle Exceptions in a PLINQ Query\"\nms.date: \"03/30/2017\"\nms.technology: dotnet-standard\ndev_langs: \n  - \"csharp\"\n  - \"vb\"\nhelpviewer_keywords: \n  - \"PLINQ queries, how to handle exceptions\"\nms.assetid: 8d56ff9b-a571-4d31-b41f-80c0b51b70a5\nauthor: \"rpetrusha\"\nms.author: \"ronpet\"","nodes":[{"content":"How to: Handle Exceptions in a PLINQ Query","nodes":[{"pos":[0,42],"content":"How to: Handle Exceptions in a PLINQ Query","nodes":[{"content":"How to: Handle Exceptions in a PLINQ Query","pos":[0,42]}]}],"path":["title"],"nosxs":false}],"yml":true},{"pos":[306,348],"content":"How to: Handle Exceptions in a PLINQ Query","linkify":"How to: Handle Exceptions in a PLINQ Query","nodes":[{"content":"How to: Handle Exceptions in a PLINQ Query","pos":[0,42]}]},{"content":"The first example in this topic shows how to handle the <ph id=\"ph1\">&lt;xref:System.AggregateException?displayProperty=nameWithType&gt;</ph> that can be thrown from a PLINQ query when it executes.","pos":[349,522],"source":"The first example in this topic shows how to handle the <xref:System.AggregateException?displayProperty=nameWithType> that can be thrown from a PLINQ query when it executes."},{"content":"The second example shows how to put try-catch blocks within delegates, as close as possible to where the exception will be thrown.","pos":[523,653]},{"content":"In this way, you can catch them as soon as they occur and possibly continue query execution.","pos":[654,746]},{"content":"When exceptions are allowed to bubble up back to the joining thread, then it is possible that a query may continue to process some items after the exception is raised.","pos":[747,914]},{"content":"In some cases when PLINQ falls back to sequential execution, and an exception occurs, the exception may be propagated directly, and not wrapped in an <ph id=\"ph1\">&lt;xref:System.AggregateException&gt;</ph>.","pos":[921,1104],"source":"In some cases when PLINQ falls back to sequential execution, and an exception occurs, the exception may be propagated directly, and not wrapped in an <xref:System.AggregateException>."},{"content":"Also, <ph id=\"ph1\">&lt;xref:System.Threading.ThreadAbortException&gt;</ph>s are always propagated directly.","pos":[1105,1188],"source":" Also, <xref:System.Threading.ThreadAbortException>s are always propagated directly."},{"pos":[1196,1668],"content":"[!NOTE]\n When \"Just My Code\" is enabled, Visual Studio will break on the line that throws the exception and display an error message that says \"exception not handled by user code.\" This error is benign. You can press F5 to continue from it, and see the exception-handling behavior that is demonstrated in the examples below. To prevent Visual Studio from breaking on the first error, just uncheck the \"Just My Code\" checkbox under **Tools, Options, Debugging, General**.","leadings":["","> "],"nodes":[{"content":"When \"Just My Code\" is enabled, Visual Studio will break on the line that throws the exception and display an error message that says \"exception not handled by user code.\" This error is benign. You can press F5 to continue from it, and see the exception-handling behavior that is demonstrated in the examples below. To prevent Visual Studio from breaking on the first error, just uncheck the \"Just My Code\" checkbox under **Tools, Options, Debugging, General**.","pos":[9,470],"nodes":[{"content":"When \"Just My Code\" is enabled, Visual Studio will break on the line that throws the exception and display an error message that says \"exception not handled by user code.\"","pos":[0,171]},{"content":"This error is benign.","pos":[172,193]},{"content":"You can press F5 to continue from it, and see the exception-handling behavior that is demonstrated in the examples below.","pos":[194,315]},{"content":"To prevent Visual Studio from breaking on the first error, just uncheck the \"Just My Code\" checkbox under <bpt id=\"p1\">**</bpt>Tools, Options, Debugging, General<ept id=\"p1\">**</ept>.","pos":[316,461],"source":" To prevent Visual Studio from breaking on the first error, just uncheck the \"Just My Code\" checkbox under **Tools, Options, Debugging, General**."}]}]},{"content":"This example is intended to demonstrate usage, and might not run faster than the equivalent sequential LINQ to Objects query.","pos":[1679,1804]},{"content":"For more information about speedup, see <bpt id=\"p1\">[</bpt>Understanding Speedup in PLINQ<ept id=\"p1\">](../../../docs/standard/parallel-programming/understanding-speedup-in-plinq.md)</ept>.","pos":[1805,1957],"source":" For more information about speedup, see [Understanding Speedup in PLINQ](../../../docs/standard/parallel-programming/understanding-speedup-in-plinq.md)."},{"pos":[1966,1973],"content":"Example","linkify":"Example","nodes":[{"content":"Example","pos":[0,7]}]},{"pos":[1977,2160],"content":"This example shows how to put the try-catch blocks around the code that executes the query to catch any <ph id=\"ph1\">&lt;xref:System.AggregateException?displayProperty=nameWithType&gt;</ph>s that are thrown.","source":"This example shows how to put the try-catch blocks around the code that executes the query to catch any <xref:System.AggregateException?displayProperty=nameWithType>s that are thrown."},{"content":"In this example, the query cannot continue after the exception is thrown.","pos":[2385,2458]},{"content":"By the time your application code catches the exception, PLINQ has already stopped the query on all threads.","pos":[2459,2567]},{"pos":[2576,2583],"content":"Example","linkify":"Example","nodes":[{"content":"Example","pos":[0,7]}]},{"content":"The following example shows how to put a try-catch block in a delegate to make it possible to catch an exception and continue with the query execution.","pos":[2587,2738]},{"pos":[2965,2983],"content":"Compiling the Code","linkify":"Compiling the Code","nodes":[{"content":"Compiling the Code","pos":[0,18]}]},{"content":"To compile and run these examples, copy them into the PLINQ Data Sample example and call the method from Main.","pos":[2993,3103]},{"pos":[3112,3130],"content":"Robust Programming","linkify":"Robust Programming","nodes":[{"content":"Robust Programming","pos":[0,18]}]},{"content":"Do not catch an exception unless you know how to handle it so that you do not corrupt the state of your program.","pos":[3134,3246]},{"pos":[3255,3263],"content":"See also","linkify":"See also","nodes":[{"content":"See also","pos":[0,8]}]},{"pos":[3307,3398],"content":"<bpt id=\"p1\">[</bpt>Parallel LINQ (PLINQ)<ept id=\"p1\">](../../../docs/standard/parallel-programming/parallel-linq-plinq.md)</ept>","source":"[Parallel LINQ (PLINQ)](../../../docs/standard/parallel-programming/parallel-linq-plinq.md)"}]}