{"content":"---\ntitle: \"&#39;Catch&#39; cannot appear after &#39;Finally&#39; within a &#39;Try&#39; statement | Microsoft Docs\"\n\nms.date: \"2015-07-20\"\nms.prod: .net\n\n\nms.technology: \n  - \"devlang-visual-basic\"\n\nms.topic: \"article\"\nf1_keywords: \n  - \"vbc30379\"\n  - \"bc30379\"\nhelpviewer_keywords: \n  - \"BC30379\"\nms.assetid: 33d1278b-cf10-4c66-aaf8-08a4372f370b\ncaps.latest.revision: 8\nauthor: dotnet-bot\nms.author: dotnetcontent\n\ntranslation.priority.ht: \n  - \"de-de\"\n  - \"es-es\"\n  - \"fr-fr\"\n  - \"it-it\"\n  - \"ja-jp\"\n  - \"ko-kr\"\n  - \"ru-ru\"\n  - \"zh-cn\"\n  - \"zh-tw\"\ntranslation.priority.mt: \n  - \"cs-cz\"\n  - \"pl-pl\"\n  - \"pt-br\"\n  - \"tr-tr\"\n---\n# &#39;Catch&#39; cannot appear after &#39;Finally&#39; within a &#39;Try&#39; statement\nA `Catch` statement appears in the code after the `Finally` ending a `Try` statement block. `Catch` must appear within a `Try...Catch...Finally` statement block.  \n  \n **Error ID:** BC30379  \n  \n## To correct this error  \n  \n1.  Move the `Catch` statement to a more appropriate place in the code.  \n  \n## See Also  \n [Try...Catch...Finally Statement](../../visual-basic/language-reference/statements/try-catch-finally-statement.md)   \n [Structured Exception Handling Overview for Visual Basic](http://msdn.microsoft.com/en-us/bb81af80-a735-4873-9711-6151a48e418a)","nodes":[{"pos":[4,624],"nodes":[{"content":"&#39;Catch&#39; cannot appear after &#39;Finally&#39; within a &#39;Try&#39; statement | Microsoft Docs","nodes":[{"pos":[0,103],"content":"&#39;Catch&#39; cannot appear after &#39;Finally&#39; within a &#39;Try&#39; statement | Microsoft Docs","nodes":[{"content":"&amp;#39;Catch&amp;#39; cannot appear after &amp;#39;Finally&amp;#39; within a &amp;#39;Try&amp;#39; statement | Microsoft Docs","pos":[0,103],"source":"&#39;Catch&#39; cannot appear after &#39;Finally&#39; within a &#39;Try&#39; statement | Microsoft Docs"}]}],"pos":[6,112],"yaml":true}],"content":"title: \"&#39;Catch&#39; cannot appear after &#39;Finally&#39; within a &#39;Try&#39; statement | Microsoft Docs\"\n\nms.date: \"2015-07-20\"\nms.prod: .net\n\n\nms.technology: \n  - \"devlang-visual-basic\"\n\nms.topic: \"article\"\nf1_keywords: \n  - \"vbc30379\"\n  - \"bc30379\"\nhelpviewer_keywords: \n  - \"BC30379\"\nms.assetid: 33d1278b-cf10-4c66-aaf8-08a4372f370b\ncaps.latest.revision: 8\nauthor: dotnet-bot\nms.author: dotnetcontent\n\ntranslation.priority.ht: \n  - \"de-de\"\n  - \"es-es\"\n  - \"fr-fr\"\n  - \"it-it\"\n  - \"ja-jp\"\n  - \"ko-kr\"\n  - \"ru-ru\"\n  - \"zh-cn\"\n  - \"zh-tw\"\ntranslation.priority.mt: \n  - \"cs-cz\"\n  - \"pl-pl\"\n  - \"pt-br\"\n  - \"tr-tr\"","yamlblock":true},{"pos":[631,717],"content":"&#39;Catch&#39; cannot appear after &#39;Finally&#39; within a &#39;Try&#39; statement","linkify":"&#39;Catch&#39; cannot appear after &#39;Finally&#39; within a &#39;Try&#39; statement","nodes":[{"content":"&amp;#39;Catch&amp;#39; cannot appear after &amp;#39;Finally&amp;#39; within a &amp;#39;Try&amp;#39; statement","pos":[0,86],"source":"&#39;Catch&#39; cannot appear after &#39;Finally&#39; within a &#39;Try&#39; statement"}]},{"content":"A <ph id=\"ph1\">`Catch`</ph> statement appears in the code after the <ph id=\"ph2\">`Finally`</ph> ending a <ph id=\"ph3\">`Try`</ph> statement block.","pos":[718,809],"source":"A `Catch` statement appears in the code after the `Finally` ending a `Try` statement block."},{"content":"<ph id=\"ph1\">`Catch`</ph> must appear within a <ph id=\"ph2\">`Try...Catch...Finally`</ph> statement block.","pos":[810,879],"source":"`Catch` must appear within a `Try...Catch...Finally` statement block."},{"pos":[886,907],"content":"<bpt id=\"p1\">**</bpt>Error ID:<ept id=\"p1\">**</ept> BC30379","source":"**Error ID:** BC30379"},{"pos":[916,937],"content":"To correct this error","linkify":"To correct this error","nodes":[{"content":"To correct this error","pos":[0,21]}]},{"pos":[947,1014],"content":"Move the <ph id=\"ph1\">`Catch`</ph> statement to a more appropriate place in the code.","source":"Move the `Catch` statement to a more appropriate place in the code."},{"pos":[1023,1031],"content":"See Also","linkify":"See Also","nodes":[{"content":"See Also","pos":[0,8]}]},{"content":"<bpt id=\"p1\">[</bpt>Try...Catch...Finally Statement<ept id=\"p1\">](../../visual-basic/language-reference/statements/try-catch-finally-statement.md)</ept><ph id=\"ph1\"> </ph>","pos":[1035,1150],"source":"[Try...Catch...Finally Statement](../../visual-basic/language-reference/statements/try-catch-finally-statement.md) "},{"content":"<bpt id=\"p1\">[</bpt>Structured Exception Handling Overview for Visual Basic<ept id=\"p1\">](http://msdn.microsoft.com/en-us/bb81af80-a735-4873-9711-6151a48e418a)</ept>","pos":[1154,1281],"source":"[Structured Exception Handling Overview for Visual Basic](http://msdn.microsoft.com/en-us/bb81af80-a735-4873-9711-6151a48e418a)"}]}