{"content":"---\ntitle: \"'Throw' operand must derive from 'System.Exception'\"\nms.date: 07/20/2015\nf1_keywords: \n  - \"vbc30665\"\n  - \"bc30665\"\nhelpviewer_keywords: \n  - \"BC30665\"\nms.assetid: 7c228087-39ea-4b30-a410-6ba711e67e5e\n---\n# 'Throw' operand must derive from 'System.Exception'\nThe argument supplied to `Throw` must either be an instance of `System.Exception` or an instance of a class derived from `System.Exception`.  \n  \n **Error ID:** BC30665  \n  \n## To correct this error  \n  \n-   Use an argument derived from `System.Exception`, as in the following example.  \n  \n    ```vb\n    Throw New System.Exception(\"This is an error.\")  \n    ```  \n  \n## See also\n\n- [Throw Statement](../../visual-basic/language-reference/statements/throw-statement.md)\n- [Try...Catch...Finally Statement](../../visual-basic/language-reference/statements/try-catch-finally-statement.md)\n- <xref:System.Exception?displayProperty=nameWithType>\n- [Handling and throwing exceptions in .NET](../../standard/exceptions/index.md)\n","nodes":[{"pos":[4,212],"embed":true,"restype":"x-metadata","content":"title: \"'Throw' operand must derive from 'System.Exception'\"\nms.date: 07/20/2015\nf1_keywords: \n  - \"vbc30665\"\n  - \"bc30665\"\nhelpviewer_keywords: \n  - \"BC30665\"\nms.assetid: 7c228087-39ea-4b30-a410-6ba711e67e5e","nodes":[{"content":"'Throw' operand must derive from 'System.Exception'","nodes":[{"pos":[0,51],"content":"'Throw' operand must derive from 'System.Exception'","nodes":[{"content":"'Throw' operand must derive from 'System.Exception'","pos":[0,51]}]}],"path":["title"],"nosxs":false}],"yml":true},{"pos":[219,270],"content":"'Throw' operand must derive from 'System.Exception'","linkify":"'Throw' operand must derive from 'System.Exception'","nodes":[{"content":"'Throw' operand must derive from 'System.Exception'","pos":[0,51]}]},{"pos":[271,411],"content":"The argument supplied to <ph id=\"ph1\">`Throw`</ph> must either be an instance of <ph id=\"ph2\">`System.Exception`</ph> or an instance of a class derived from <ph id=\"ph3\">`System.Exception`</ph>.","source":"The argument supplied to `Throw` must either be an instance of `System.Exception` or an instance of a class derived from `System.Exception`."},{"pos":[418,439],"content":"<bpt id=\"p1\">**</bpt>Error ID:<ept id=\"p1\">**</ept> BC30665","source":"**Error ID:** BC30665"},{"pos":[448,469],"content":"To correct this error","linkify":"To correct this error","nodes":[{"content":"To correct this error","pos":[0,21]}]},{"pos":[479,556],"content":"Use an argument derived from <ph id=\"ph1\">`System.Exception`</ph>, as in the following example.","source":"Use an argument derived from `System.Exception`, as in the following example."},{"pos":[642,650],"content":"See also","linkify":"See also","nodes":[{"content":"See also","pos":[0,8]}]},{"pos":[654,740],"content":"<bpt id=\"p1\">[</bpt>Throw Statement<ept id=\"p1\">](../../visual-basic/language-reference/statements/throw-statement.md)</ept>","source":"[Throw Statement](../../visual-basic/language-reference/statements/throw-statement.md)"},{"pos":[743,857],"content":"<bpt id=\"p1\">[</bpt>Try...Catch...Finally Statement<ept id=\"p1\">](../../visual-basic/language-reference/statements/try-catch-finally-statement.md)</ept>","source":"[Try...Catch...Finally Statement](../../visual-basic/language-reference/statements/try-catch-finally-statement.md)"},{"pos":[915,993],"content":"<bpt id=\"p1\">[</bpt>Handling and throwing exceptions in .NET<ept id=\"p1\">](../../standard/exceptions/index.md)</ept>","source":"[Handling and throwing exceptions in .NET](../../standard/exceptions/index.md)"}]}