{"content":"---\ntitle: \"&#39;Catch&#39; block never reached; &lt;exception&gt; handled above in the same &#39;Try&#39; statement | Microsoft Docs\"\n\nms.date: \"2015-07-20\"\nms.prod: .net\n\n\nms.technology: \n  - \"devlang-visual-basic\"\n\nms.topic: \"article\"\nf1_keywords: \n  - \"bc42031\"\n  - \"vbc42031\"\nhelpviewer_keywords: \n  - \"BC42031\"\nms.assetid: 7d15597c-5988-42ea-a853-63cbf78faaf3\ncaps.latest.revision: 10\nauthor: dotnet-bot\nms.author: dotnetcontent\n\ntranslation.priority.ht: \n  - \"de-de\"\n  - \"es-es\"\n  - \"fr-fr\"\n  - \"it-it\"\n  - \"ja-jp\"\n  - \"ko-kr\"\n  - \"ru-ru\"\n  - \"zh-cn\"\n  - \"zh-tw\"\ntranslation.priority.mt: \n  - \"cs-cz\"\n  - \"pl-pl\"\n  - \"pt-br\"\n  - \"tr-tr\"\n---\n# &#39;Catch&#39; block never reached; &lt;exception&gt; handled above in the same &#39;Try&#39; statement\nA `Catch` block in the code cannot be reached because it is handled in a preceding `Try` block.  \n  \n By default, this message is a warning. For more information about hiding warnings or treating warnings as errors, please see [Configuring Warnings in Visual Basic](https://docs.microsoft.com/visualstudio/ide/configuring-warnings-in-visual-basic)  \n  \n **Error ID:** BC42031  \n  \n## To correct this error  \n  \n-   Remove the redundant statement.  \n  \n## See Also  \n [How to: Catch an Exception in Visual Basic](http://msdn.microsoft.com/en-us/f3063c89-d2bf-49b1-91b5-b87edfb18b95)   \n [How to: Test Code with a Try…Catch Block in Visual Basic](http://msdn.microsoft.com/en-us/8368e205-ed73-4185-a247-af84fb4fafa9)   \n [How to: Filter Errors in a Catch Block in Visual Basic](http://msdn.microsoft.com/en-us/85964d0a-56e7-4301-a96e-5eaea23b7b9b)   \n [Walkthrough: Structured Exception Handling (Visual Basic)](http://msdn.microsoft.com/en-us/440da655-4b32-490b-8b16-bfe46f41fa76)   \n [Try...Catch...Finally Statement](../../visual-basic/language-reference/statements/try-catch-finally-statement.md)","nodes":[{"pos":[4,643],"nodes":[{"content":"&#39;Catch&#39; block never reached; &lt;exception&gt; handled above in the same &#39;Try&#39; statement | Microsoft Docs","nodes":[{"pos":[0,121],"content":"&#39;Catch&#39; block never reached; &lt;exception&gt; handled above in the same &#39;Try&#39; statement | Microsoft Docs","nodes":[{"content":"&amp;#39;Catch&amp;#39; block never reached; <ph id=\"ph1\">&amp;lt;</ph>exception<ph id=\"ph2\">&amp;gt;</ph> handled above in the same &amp;#39;Try&amp;#39; statement | Microsoft Docs","pos":[0,121],"source":"&#39;Catch&#39; block never reached; &lt;exception&gt; handled above in the same &#39;Try&#39; statement | Microsoft Docs"}]}],"pos":[6,130],"yaml":true}],"content":"title: \"&#39;Catch&#39; block never reached; &lt;exception&gt; handled above in the same &#39;Try&#39; statement | Microsoft Docs\"\n\nms.date: \"2015-07-20\"\nms.prod: .net\n\n\nms.technology: \n  - \"devlang-visual-basic\"\n\nms.topic: \"article\"\nf1_keywords: \n  - \"bc42031\"\n  - \"vbc42031\"\nhelpviewer_keywords: \n  - \"BC42031\"\nms.assetid: 7d15597c-5988-42ea-a853-63cbf78faaf3\ncaps.latest.revision: 10\nauthor: dotnet-bot\nms.author: dotnetcontent\n\ntranslation.priority.ht: \n  - \"de-de\"\n  - \"es-es\"\n  - \"fr-fr\"\n  - \"it-it\"\n  - \"ja-jp\"\n  - \"ko-kr\"\n  - \"ru-ru\"\n  - \"zh-cn\"\n  - \"zh-tw\"\ntranslation.priority.mt: \n  - \"cs-cz\"\n  - \"pl-pl\"\n  - \"pt-br\"\n  - \"tr-tr\"","yamlblock":true},{"pos":[650,754],"content":"&#39;Catch&#39; block never reached; &lt;exception&gt; handled above in the same &#39;Try&#39; statement","linkify":"&#39;Catch&#39; block never reached; &lt;exception&gt; handled above in the same &#39;Try&#39; statement","nodes":[{"content":"&amp;#39;Catch&amp;#39; block never reached; <ph id=\"ph1\">&amp;lt;</ph>exception<ph id=\"ph2\">&amp;gt;</ph> handled above in the same &amp;#39;Try&amp;#39; statement","pos":[0,104],"source":"&#39;Catch&#39; block never reached; &lt;exception&gt; handled above in the same &#39;Try&#39; statement"}]},{"pos":[755,850],"content":"A <ph id=\"ph1\">`Catch`</ph> block in the code cannot be reached because it is handled in a preceding <ph id=\"ph2\">`Try`</ph> block.","source":"A `Catch` block in the code cannot be reached because it is handled in a preceding `Try` block."},{"content":"By default, this message is a warning.","pos":[857,895]},{"content":"For more information about hiding warnings or treating warnings as errors, please see <bpt id=\"p1\">[</bpt>Configuring Warnings in Visual Basic<ept id=\"p1\">](https://docs.microsoft.com/visualstudio/ide/configuring-warnings-in-visual-basic)</ept>","pos":[896,1102],"source":" For more information about hiding warnings or treating warnings as errors, please see [Configuring Warnings in Visual Basic](https://docs.microsoft.com/visualstudio/ide/configuring-warnings-in-visual-basic)"},{"pos":[1109,1130],"content":"<bpt id=\"p1\">**</bpt>Error ID:<ept id=\"p1\">**</ept> BC42031","source":"**Error ID:** BC42031"},{"pos":[1139,1160],"content":"To correct this error","linkify":"To correct this error","nodes":[{"content":"To correct this error","pos":[0,21]}]},{"content":"Remove the redundant statement.","pos":[1170,1201]},{"pos":[1210,1218],"content":"See Also","linkify":"See Also","nodes":[{"content":"See Also","pos":[0,8]}]},{"content":"<bpt id=\"p1\">[</bpt>How to: Catch an Exception in Visual Basic<ept id=\"p1\">](http://msdn.microsoft.com/en-us/f3063c89-d2bf-49b1-91b5-b87edfb18b95)</ept><ph id=\"ph1\"> </ph>","pos":[1222,1337],"source":"[How to: Catch an Exception in Visual Basic](http://msdn.microsoft.com/en-us/f3063c89-d2bf-49b1-91b5-b87edfb18b95) "},{"content":"<bpt id=\"p1\">[</bpt>How to: Test Code with a Try…Catch Block in Visual Basic<ept id=\"p1\">](http://msdn.microsoft.com/en-us/8368e205-ed73-4185-a247-af84fb4fafa9)</ept><ph id=\"ph1\"> </ph>","pos":[1341,1470],"source":"[How to: Test Code with a Try…Catch Block in Visual Basic](http://msdn.microsoft.com/en-us/8368e205-ed73-4185-a247-af84fb4fafa9) "},{"content":"<bpt id=\"p1\">[</bpt>How to: Filter Errors in a Catch Block in Visual Basic<ept id=\"p1\">](http://msdn.microsoft.com/en-us/85964d0a-56e7-4301-a96e-5eaea23b7b9b)</ept><ph id=\"ph1\"> </ph>","pos":[1474,1601],"source":"[How to: Filter Errors in a Catch Block in Visual Basic](http://msdn.microsoft.com/en-us/85964d0a-56e7-4301-a96e-5eaea23b7b9b) "},{"content":"<bpt id=\"p1\">[</bpt>Walkthrough: Structured Exception Handling (Visual Basic)<ept id=\"p1\">](http://msdn.microsoft.com/en-us/440da655-4b32-490b-8b16-bfe46f41fa76)</ept><ph id=\"ph1\"> </ph>","pos":[1605,1735],"source":"[Walkthrough: Structured Exception Handling (Visual Basic)](http://msdn.microsoft.com/en-us/440da655-4b32-490b-8b16-bfe46f41fa76) "},{"content":"<bpt id=\"p1\">[</bpt>Try...Catch...Finally Statement<ept id=\"p1\">](../../visual-basic/language-reference/statements/try-catch-finally-statement.md)</ept>","pos":[1739,1853],"source":"[Try...Catch...Finally Statement](../../visual-basic/language-reference/statements/try-catch-finally-statement.md)"}]}