{"content":"---\ntitle: \"How to: Listen for Multiple Cancellation Requests\"\nms.date: \"03/30/2017\"\nms.technology: dotnet-standard\ndev_langs: \n  - \"csharp\"\n  - \"vb\"\nhelpviewer_keywords: \n  - \"cancellation tokens, joining\"\n  - \"LinkedTokenSource, how to\"\nms.assetid: 6f4f3804-2ed7-41b4-a97a-6e32b93f6e05\nauthor: \"rpetrusha\"\nms.author: \"ronpet\"\n---\n# How to: Listen for Multiple Cancellation Requests\nThis example shows how to listen to two cancellation tokens simultaneously so that you can cancel an operation if either token requests it.  \n  \n> [!NOTE]\n>  When \"Just My Code\" is enabled, Visual Studio in some cases will break on the line that throws the exception and display an error message that says \"exception not handled by user code.\" This error is benign. You can press F5 to continue from it, and see the exception-handling behavior that is demonstrated in the examples below. To prevent Visual Studio from breaking on the first error, just uncheck the \"Just My Code\" checkbox under **Tools, Options, Debugging, General**.  \n  \n## Example  \n In the following example, the <xref:System.Threading.CancellationTokenSource.CreateLinkedTokenSource%2A> method is used to join two tokens into one token. This enables the token to be passed to methods that take just one cancellation token as an argument. The example demonstrates a common scenario in which a method must observe both a token passed in from outside the class, and a token generated inside the class.  \n  \n [!code-csharp[Cancellation#13](../../../samples/snippets/csharp/VS_Snippets_Misc/cancellation/cs/cancellationex13.cs#13)]\n [!code-vb[Cancellation#13](../../../samples/snippets/visualbasic/VS_Snippets_Misc/cancellation/vb/cancellationex13.vb#13)]  \n  \n When the linked token throws an <xref:System.OperationCanceledException>, the token that is passed to the exception is the linked token, not either of the predecessor tokens. To determine which of the tokens was canceled, check the status of the predecessor tokens directly.  \n  \n In this example, <xref:System.AggregateException> should never be thrown, but it is caught here because in real-world scenarios any other exceptions besides <xref:System.OperationCanceledException> that are thrown from the task delegate are wrapped in a <xref:System.AggregateException>.  \n  \n## See also\n\n- [Cancellation in Managed Threads](../../../docs/standard/threading/cancellation-in-managed-threads.md)\n","nodes":[{"pos":[4,327],"embed":true,"restype":"x-metadata","content":"title: \"How to: Listen for Multiple Cancellation Requests\"\nms.date: \"03/30/2017\"\nms.technology: dotnet-standard\ndev_langs: \n  - \"csharp\"\n  - \"vb\"\nhelpviewer_keywords: \n  - \"cancellation tokens, joining\"\n  - \"LinkedTokenSource, how to\"\nms.assetid: 6f4f3804-2ed7-41b4-a97a-6e32b93f6e05\nauthor: \"rpetrusha\"\nms.author: \"ronpet\"","nodes":[{"content":"How to: Listen for Multiple Cancellation Requests","nodes":[{"pos":[0,49],"content":"How to: Listen for Multiple Cancellation Requests","nodes":[{"content":"How to: Listen for Multiple Cancellation Requests","pos":[0,49]}]}],"path":["title"],"nosxs":false}],"yml":true},{"pos":[334,383],"content":"How to: Listen for Multiple Cancellation Requests","linkify":"How to: Listen for Multiple Cancellation Requests","nodes":[{"content":"How to: Listen for Multiple Cancellation Requests","pos":[0,49]}]},{"content":"This example shows how to listen to two cancellation tokens simultaneously so that you can cancel an operation if either token requests it.","pos":[384,523]},{"pos":[531,1017],"content":"[!NOTE]\n When \"Just My Code\" is enabled, Visual Studio in some cases will break on the line that throws the exception and display an error message that says \"exception not handled by user code.\" This error is benign. You can press F5 to continue from it, and see the exception-handling behavior that is demonstrated in the examples below. To prevent Visual Studio from breaking on the first error, just uncheck the \"Just My Code\" checkbox under **Tools, Options, Debugging, General**.","leadings":["","> "],"nodes":[{"content":"When \"Just My Code\" is enabled, Visual Studio in some cases will break on the line that throws the exception and display an error message that says \"exception not handled by user code.\" This error is benign. You can press F5 to continue from it, and see the exception-handling behavior that is demonstrated in the examples below. To prevent Visual Studio from breaking on the first error, just uncheck the \"Just My Code\" checkbox under **Tools, Options, Debugging, General**.","pos":[9,484],"nodes":[{"content":"When \"Just My Code\" is enabled, Visual Studio in some cases will break on the line that throws the exception and display an error message that says \"exception not handled by user code.\"","pos":[0,185]},{"content":"This error is benign.","pos":[186,207]},{"content":"You can press F5 to continue from it, and see the exception-handling behavior that is demonstrated in the examples below.","pos":[208,329]},{"content":"To prevent Visual Studio from breaking on the first error, just uncheck the \"Just My Code\" checkbox under <bpt id=\"p1\">**</bpt>Tools, Options, Debugging, General<ept id=\"p1\">**</ept>.","pos":[330,475],"source":" To prevent Visual Studio from breaking on the first error, just uncheck the \"Just My Code\" checkbox under **Tools, Options, Debugging, General**."}]}]},{"pos":[1026,1033],"content":"Example","linkify":"Example","nodes":[{"content":"Example","pos":[0,7]}]},{"content":"In the following example, the <ph id=\"ph1\">&lt;xref:System.Threading.CancellationTokenSource.CreateLinkedTokenSource%2A&gt;</ph> method is used to join two tokens into one token.","pos":[1037,1191],"source":"In the following example, the <xref:System.Threading.CancellationTokenSource.CreateLinkedTokenSource%2A> method is used to join two tokens into one token."},{"content":"This enables the token to be passed to methods that take just one cancellation token as an argument.","pos":[1192,1292]},{"content":"The example demonstrates a common scenario in which a method must observe both a token passed in from outside the class, and a token generated inside the class.","pos":[1293,1453]},{"content":"When the linked token throws an <ph id=\"ph1\">&lt;xref:System.OperationCanceledException&gt;</ph>, the token that is passed to the exception is the linked token, not either of the predecessor tokens.","pos":[1712,1886],"source":"When the linked token throws an <xref:System.OperationCanceledException>, the token that is passed to the exception is the linked token, not either of the predecessor tokens."},{"content":"To determine which of the tokens was canceled, check the status of the predecessor tokens directly.","pos":[1887,1986]},{"pos":[1993,2280],"content":"In this example, <ph id=\"ph1\">&lt;xref:System.AggregateException&gt;</ph> should never be thrown, but it is caught here because in real-world scenarios any other exceptions besides <ph id=\"ph2\">&lt;xref:System.OperationCanceledException&gt;</ph> that are thrown from the task delegate are wrapped in a <ph id=\"ph3\">&lt;xref:System.AggregateException&gt;</ph>.","source":"In this example, <xref:System.AggregateException> should never be thrown, but it is caught here because in real-world scenarios any other exceptions besides <xref:System.OperationCanceledException> that are thrown from the task delegate are wrapped in a <xref:System.AggregateException>."},{"pos":[2289,2297],"content":"See also","linkify":"See also","nodes":[{"content":"See also","pos":[0,8]}]},{"pos":[2301,2403],"content":"<bpt id=\"p1\">[</bpt>Cancellation in Managed Threads<ept id=\"p1\">](../../../docs/standard/threading/cancellation-in-managed-threads.md)</ept>","source":"[Cancellation in Managed Threads](../../../docs/standard/threading/cancellation-in-managed-threads.md)"}]}