{"content":"---\ntitle: \"How to: Execute Cleanup Code Using finally - C# Programming Guide\"\nms.custom: seodec18\nms.date: 07/20/2015\nhelpviewer_keywords: \n  - \"try/finally blocks [C#]\"\n  - \"exceptions [C#], try/finally block\"\n  - \"exception handling [C#], try/finally block\"\nms.assetid: 1b1e5aef-3f32-4a88-9d39-b5fffb33bdaf\n---\n# How to: Execute Cleanup Code Using finally (C# Programming Guide)\nThe purpose of a `finally` statement is to ensure that the necessary cleanup of objects, usually objects that are holding external resources, occurs immediately, even if an exception is thrown. One example of such cleanup is calling <xref:System.IO.Stream.Close%2A> on a <xref:System.IO.FileStream> immediately after use instead of waiting for the object to be garbage collected by the common language runtime, as follows:  \n  \n [!code-csharp[csProgGuideExceptions#16](~/samples/snippets/csharp/VS_Snippets_VBCSharp/csProgGuideExceptions/CS/Exceptions.cs#16)]  \n  \n## Example  \n To turn the previous code into a `try-catch-finally` statement, the cleanup code is separated from the working code, as follows.  \n  \n [!code-csharp[csProgGuideExceptions#17](~/samples/snippets/csharp/VS_Snippets_VBCSharp/csProgGuideExceptions/CS/Exceptions.cs#17)]  \n  \n Because an exception can occur at any time within the `try` block before the `OpenWrite()` call, or the `OpenWrite()` call itself could fail, we are not guaranteed that the file is open when we try to close it. The `finally` block adds a check to make sure that the <xref:System.IO.FileStream> object is not `null` before you call the <xref:System.IO.Stream.Close%2A> method. Without the `null` check, the `finally` block could throw its own <xref:System.NullReferenceException>, but throwing exceptions in `finally` blocks should be avoided if it is possible.  \n  \n A database connection is another good candidate for being closed in a `finally` block. Because the number of connections allowed to a database server is sometimes limited, you should close database connections as quickly as possible. If an exception is thrown before you can close your connection, this is another case where using the `finally` block is better than waiting for garbage collection.  \n  \n## See also\n\n- [C# Programming Guide](../../../csharp/programming-guide/index.md)\n- [Exceptions and Exception Handling](../../../csharp/programming-guide/exceptions/index.md)\n- [Exception Handling](../../../csharp/programming-guide/exceptions/exception-handling.md)\n- [using Statement](../../../csharp/language-reference/keywords/using-statement.md)\n- [try-catch](../../../csharp/language-reference/keywords/try-catch.md)\n- [try-finally](../../../csharp/language-reference/keywords/try-finally.md)\n- [try-catch-finally](../../../csharp/language-reference/keywords/try-catch-finally.md)\n","nodes":[{"pos":[4,309],"embed":true,"restype":"x-metadata","content":"title: \"How to: Execute Cleanup Code Using finally - C# Programming Guide\"\nms.custom: seodec18\nms.date: 07/20/2015\nhelpviewer_keywords: \n  - \"try/finally blocks [C#]\"\n  - \"exceptions [C#], try/finally block\"\n  - \"exception handling [C#], try/finally block\"\nms.assetid: 1b1e5aef-3f32-4a88-9d39-b5fffb33bdaf","nodes":[{"content":"How to: Execute Cleanup Code Using finally - C# Programming Guide","nodes":[{"pos":[0,65],"content":"How to: Execute Cleanup Code Using finally - C# Programming Guide","nodes":[{"content":"How to: Execute Cleanup Code Using finally - C# Programming Guide","pos":[0,65]}]}],"path":["title"],"nosxs":false}],"yml":true},{"pos":[316,381],"content":"How to: Execute Cleanup Code Using finally (C# Programming Guide)","linkify":"How to: Execute Cleanup Code Using finally (C# Programming Guide)","nodes":[{"content":"How to: Execute Cleanup Code Using finally (C# Programming Guide)","pos":[0,65]}]},{"content":"The purpose of a <ph id=\"ph1\">`finally`</ph> statement is to ensure that the necessary cleanup of objects, usually objects that are holding external resources, occurs immediately, even if an exception is thrown.","pos":[382,575],"source":"The purpose of a `finally` statement is to ensure that the necessary cleanup of objects, usually objects that are holding external resources, occurs immediately, even if an exception is thrown."},{"content":"One example of such cleanup is calling <ph id=\"ph1\">&lt;xref:System.IO.Stream.Close%2A&gt;</ph> on a <ph id=\"ph2\">&lt;xref:System.IO.FileStream&gt;</ph> immediately after use instead of waiting for the object to be garbage collected by the common language runtime, as follows:","pos":[576,804],"source":" One example of such cleanup is calling <xref:System.IO.Stream.Close%2A> on a <xref:System.IO.FileStream> immediately after use instead of waiting for the object to be garbage collected by the common language runtime, as follows:"},{"pos":[950,957],"content":"Example","linkify":"Example","nodes":[{"content":"Example","pos":[0,7]}]},{"pos":[961,1089],"content":"To turn the previous code into a <ph id=\"ph1\">`try-catch-finally`</ph> statement, the cleanup code is separated from the working code, as follows.","source":"To turn the previous code into a `try-catch-finally` statement, the cleanup code is separated from the working code, as follows."},{"content":"Because an exception can occur at any time within the <ph id=\"ph1\">`try`</ph> block before the <ph id=\"ph2\">`OpenWrite()`</ph> call, or the <ph id=\"ph3\">`OpenWrite()`</ph> call itself could fail, we are not guaranteed that the file is open when we try to close it.","pos":[1233,1443],"source":"Because an exception can occur at any time within the `try` block before the `OpenWrite()` call, or the `OpenWrite()` call itself could fail, we are not guaranteed that the file is open when we try to close it."},{"content":"The <ph id=\"ph1\">`finally`</ph> block adds a check to make sure that the <ph id=\"ph2\">&lt;xref:System.IO.FileStream&gt;</ph> object is not <ph id=\"ph3\">`null`</ph> before you call the <ph id=\"ph4\">&lt;xref:System.IO.Stream.Close%2A&gt;</ph> method.","pos":[1444,1608],"source":" The `finally` block adds a check to make sure that the <xref:System.IO.FileStream> object is not `null` before you call the <xref:System.IO.Stream.Close%2A> method."},{"content":"Without the <ph id=\"ph1\">`null`</ph> check, the <ph id=\"ph2\">`finally`</ph> block could throw its own <ph id=\"ph3\">&lt;xref:System.NullReferenceException&gt;</ph>, but throwing exceptions in <ph id=\"ph4\">`finally`</ph> blocks should be avoided if it is possible.","pos":[1609,1793],"source":" Without the `null` check, the `finally` block could throw its own <xref:System.NullReferenceException>, but throwing exceptions in `finally` blocks should be avoided if it is possible."},{"content":"A database connection is another good candidate for being closed in a <ph id=\"ph1\">`finally`</ph> block.","pos":[1800,1886],"source":"A database connection is another good candidate for being closed in a `finally` block."},{"content":"Because the number of connections allowed to a database server is sometimes limited, you should close database connections as quickly as possible.","pos":[1887,2033]},{"content":"If an exception is thrown before you can close your connection, this is another case where using the <ph id=\"ph1\">`finally`</ph> block is better than waiting for garbage collection.","pos":[2034,2197],"source":" If an exception is thrown before you can close your connection, this is another case where using the `finally` block is better than waiting for garbage collection."},{"pos":[2206,2214],"content":"See also","linkify":"See also","nodes":[{"content":"See also","pos":[0,8]}]},{"pos":[2218,2284],"content":"<bpt id=\"p1\">[</bpt>C# Programming Guide<ept id=\"p1\">](../../../csharp/programming-guide/index.md)</ept>","source":"[C# Programming Guide](../../../csharp/programming-guide/index.md)"},{"pos":[2287,2377],"content":"<bpt id=\"p1\">[</bpt>Exceptions and Exception Handling<ept id=\"p1\">](../../../csharp/programming-guide/exceptions/index.md)</ept>","source":"[Exceptions and Exception Handling](../../../csharp/programming-guide/exceptions/index.md)"},{"pos":[2380,2468],"content":"<bpt id=\"p1\">[</bpt>Exception Handling<ept id=\"p1\">](../../../csharp/programming-guide/exceptions/exception-handling.md)</ept>","source":"[Exception Handling](../../../csharp/programming-guide/exceptions/exception-handling.md)"},{"pos":[2471,2552],"content":"<bpt id=\"p1\">[</bpt>using Statement<ept id=\"p1\">](../../../csharp/language-reference/keywords/using-statement.md)</ept>","source":"[using Statement](../../../csharp/language-reference/keywords/using-statement.md)"},{"pos":[2555,2624],"content":"<bpt id=\"p1\">[</bpt>try-catch<ept id=\"p1\">](../../../csharp/language-reference/keywords/try-catch.md)</ept>","source":"[try-catch](../../../csharp/language-reference/keywords/try-catch.md)"},{"pos":[2627,2700],"content":"<bpt id=\"p1\">[</bpt>try-finally<ept id=\"p1\">](../../../csharp/language-reference/keywords/try-finally.md)</ept>","source":"[try-finally](../../../csharp/language-reference/keywords/try-finally.md)"},{"pos":[2703,2788],"content":"<bpt id=\"p1\">[</bpt>try-catch-finally<ept id=\"p1\">](../../../csharp/language-reference/keywords/try-catch-finally.md)</ept>","source":"[try-catch-finally](../../../csharp/language-reference/keywords/try-catch-finally.md)"}]}