{"content":"---\ntitle: \"'On Error' statements are not valid within 'Using' statements\"\nms.date: 07/20/2015\nf1_keywords: \n  - \"vbc36013\"\n  - \"bc36013\"\nhelpviewer_keywords: \n  - \"BC36013\"\nms.assetid: 5b399bf9-6595-46e0-a808-378f6c28568b\n---\n# 'On Error' statements are not valid within 'Using' statements\nAn `On Error` statement appears within a `Using` statement but is not valid in that context.  \n  \n **Error ID:** BC36013  \n  \n## To correct this error  \n  \n-   Use structured error handling, such as a `Try…Catch` block, in place of the `On Error` statement.  \n  \n## See also\n\n- [On Error Statement](../../visual-basic/language-reference/statements/on-error-statement.md)\n- [How to use the try/catch block to catch exceptions](../../standard/exceptions/how-to-use-the-try-catch-block-to-catch-exceptions.md)\n- [Try...Catch...Finally Statement](../../visual-basic/language-reference/statements/try-catch-finally-statement.md)\n","nodes":[{"pos":[4,222],"embed":true,"restype":"x-metadata","content":"title: \"'On Error' statements are not valid within 'Using' statements\"\nms.date: 07/20/2015\nf1_keywords: \n  - \"vbc36013\"\n  - \"bc36013\"\nhelpviewer_keywords: \n  - \"BC36013\"\nms.assetid: 5b399bf9-6595-46e0-a808-378f6c28568b","nodes":[{"content":"'On Error' statements are not valid within 'Using' statements","nodes":[{"pos":[0,61],"content":"'On Error' statements are not valid within 'Using' statements","nodes":[{"content":"'On Error' statements are not valid within 'Using' statements","pos":[0,61]}]}],"path":["title"],"nosxs":false}],"yml":true},{"pos":[229,290],"content":"'On Error' statements are not valid within 'Using' statements","linkify":"'On Error' statements are not valid within 'Using' statements","nodes":[{"content":"'On Error' statements are not valid within 'Using' statements","pos":[0,61]}]},{"pos":[291,383],"content":"An <ph id=\"ph1\">`On Error`</ph> statement appears within a <ph id=\"ph2\">`Using`</ph> statement but is not valid in that context.","source":"An `On Error` statement appears within a `Using` statement but is not valid in that context."},{"pos":[390,411],"content":"<bpt id=\"p1\">**</bpt>Error ID:<ept id=\"p1\">**</ept> BC36013","source":"**Error ID:** BC36013"},{"pos":[420,441],"content":"To correct this error","linkify":"To correct this error","nodes":[{"content":"To correct this error","pos":[0,21]}]},{"pos":[451,548],"content":"Use structured error handling, such as a <ph id=\"ph1\">`Try…Catch`</ph> block, in place of the <ph id=\"ph2\">`On Error`</ph> statement.","source":"Use structured error handling, such as a `Try…Catch` block, in place of the `On Error` statement."},{"pos":[557,565],"content":"See also","linkify":"See also","nodes":[{"content":"See also","pos":[0,8]}]},{"pos":[569,661],"content":"<bpt id=\"p1\">[</bpt>On Error Statement<ept id=\"p1\">](../../visual-basic/language-reference/statements/on-error-statement.md)</ept>","source":"[On Error Statement](../../visual-basic/language-reference/statements/on-error-statement.md)"},{"pos":[664,797],"content":"<bpt id=\"p1\">[</bpt>How to use the try/catch block to catch exceptions<ept id=\"p1\">](../../standard/exceptions/how-to-use-the-try-catch-block-to-catch-exceptions.md)</ept>","source":"[How to use the try/catch block to catch exceptions](../../standard/exceptions/how-to-use-the-try-catch-block-to-catch-exceptions.md)"},{"pos":[800,914],"content":"<bpt id=\"p1\">[</bpt>Try...Catch...Finally Statement<ept id=\"p1\">](../../visual-basic/language-reference/statements/try-catch-finally-statement.md)</ept>","source":"[Try...Catch...Finally Statement](../../visual-basic/language-reference/statements/try-catch-finally-statement.md)"}]}